import itertools

mats = {
    '2021-09-30_glues': {
        1049: {'mat': 'Гознак 200 г', 'glue': 'Хомакол 943 ВР'},
        1050: {'mat': 'Гознак 200 г', 'glue': 'Хомакол 943 ВР'},
        1051: {'mat': 'Гознак 200 г', 'glue': 'Хомакол 943 ВР'},
        1052: {'mat': 'Гознак 200 г', 'glue': 'Хомакол 943 ВР'},
        1053: {'mat': 'Гознак 200 г', 'glue': 'Хомакол 943 ВР'},
        1054: {'mat': 'Pretex 200 г', 'glue': 'Хомакол 943 ВР'},
        1055: {'mat': 'Pretex 200 г', 'glue': 'Хомакол 943 ВР'},
        1056: {'mat': 'Pretex 200 г', 'glue': 'Хомакол 943 ВР'},
        1057: {'mat': 'Pretex 200 г', 'glue': 'Хомакол 943 ВР'},
        1058: {'mat': 'Pretex 200 г', 'glue': 'Хомакол 943 ВР'},
        1059: {'mat': 'Pretex 150 г', 'glue': 'Хомакол 943 ВР'},
        1060: {'mat': 'Pretex 150 г', 'glue': 'Хомакол 943 ВР'},
        1061: {'mat': 'Pretex 150 г', 'glue': 'Хомакол 943 ВР'},
        1062: {'mat': 'Pretex 150 г', 'glue': 'Хомакол 943 ВР'},
        1063: {'mat': 'Pretex 150 г', 'glue': 'Хомакол 943 ВР'},
        1064: {'mat': 'Omega Silk 150 г', 'glue': 'Хомакол 943 ВР'},
        1065: {'mat': 'Omega Silk 150 г', 'glue': 'Хомакол 943 ВР'},
        1066: {'mat': 'Omega Silk 150 г', 'glue': 'Хомакол 943 ВР'},
        1067: {'mat': 'Omega Silk 150 г', 'glue': 'Хомакол 943 ВР'},
        1068: {'mat': 'Omega Silk 150 г', 'glue': 'Хомакол 943 ВР'},
        1069: {'mat': 'Neobond 200 г', 'glue': 'Хомакол 943 ВР'},
        1070: {'mat': 'Neobond 200 г', 'glue': 'Хомакол 943 ВР'},
        1071: {'mat': 'Neobond 200 г', 'glue': 'Хомакол 943 ВР'},
        1072: {'mat': 'Neobond 200 г', 'glue': 'Хомакол 943 ВР'},
        1073: {'mat': 'Neobond 200 г', 'glue': 'Хомакол 943 ВР'},
        1074: {'mat': 'Гознак 200 г', 'glue': 'Nollax S35.3032'},
        1075: {'mat': 'Гознак 200 г', 'glue': 'Nollax S35.3032'},
        1076: {'mat': 'Гознак 200 г', 'glue': 'Nollax S35.3032'},
        1077: {'mat': 'Гознак 200 г', 'glue': 'Nollax S35.3032'},
        1078: {'mat': 'Гознак 200 г', 'glue': 'Nollax S35.3032'},
        1079: {'mat': 'Pretex 200 г', 'glue': 'Nollax S35.3032'},
        1080: {'mat': 'Pretex 200 г', 'glue': 'Nollax S35.3032'},
        1081: {'mat': 'Pretex 200 г', 'glue': 'Nollax S35.3032'},
        1082: {'mat': 'Pretex 200 г', 'glue': 'Nollax S35.3032'},
        1083: {'mat': 'Pretex 200 г', 'glue': 'Nollax S35.3032'},
        1084: {'mat': 'Pretex 150 г', 'glue': 'Nollax S35.3032'},
        1085: {'mat': 'Pretex 150 г', 'glue': 'Nollax S35.3032'},
        1086: {'mat': 'Pretex 150 г', 'glue': 'Nollax S35.3032'},
        1087: {'mat': 'Pretex 150 г', 'glue': 'Nollax S35.3032'},
        1088: {'mat': 'Pretex 150 г', 'glue': 'Nollax S35.3032'},
        1089: {'mat': 'Omega Silk 150 г', 'glue': 'Nollax S35.3032'},
        1090: {'mat': 'Omega Silk 150 г', 'glue': 'Nollax S35.3032'},
        1091: {'mat': 'Omega Silk 150 г', 'glue': 'Nollax S35.3032'},
        1092: {'mat': 'Omega Silk 150 г', 'glue': 'Nollax S35.3032'},
        1093: {'mat': 'Omega Silk 150 г', 'glue': 'Nollax S35.3032'},
        1094: {'mat': 'Neobond 200 г', 'glue': 'Nollax S35.3032'},
        1095: {'mat': 'Neobond 200 г', 'glue': 'Nollax S35.3032'},
        1096: {'mat': 'Neobond 200 г', 'glue': 'Nollax S35.3032'},
        1097: {'mat': 'Neobond 200 г', 'glue': 'Nollax S35.3032'},
        1098: {'mat': 'Neobond 200 г', 'glue': 'Nollax S35.3032'},
        1099: {'mat': 'Гознак 200 г', 'glue': 'OpSec WRS853'},
        1100: {'mat': 'Гознак 200 г', 'glue': 'OpSec WRS853'},
        1101: {'mat': 'Гознак 200 г', 'glue': 'OpSec WRS853'},
        1102: {'mat': 'Гознак 200 г', 'glue': 'OpSec WRS853'},
        1103: {'mat': 'Гознак 200 г', 'glue': 'OpSec WRS853'},
        1104: {'mat': 'Pretex 200 г', 'glue': 'OpSec WRS853'},
        1105: {'mat': 'Pretex 200 г', 'glue': 'OpSec WRS853'},
        1106: {'mat': 'Pretex 200 г', 'glue': 'OpSec WRS853'},
        1107: {'mat': 'Pretex 200 г', 'glue': 'OpSec WRS853'},
        1108: {'mat': 'Pretex 200 г', 'glue': 'OpSec WRS853'},
        1109: {'mat': 'Pretex 150 г', 'glue': 'OpSec WRS853'},
        1110: {'mat': 'Pretex 150 г', 'glue': 'OpSec WRS853'},
        1111: {'mat': 'Pretex 150 г', 'glue': 'OpSec WRS853'},
        1112: {'mat': 'Pretex 150 г', 'glue': 'OpSec WRS853'},
        1113: {'mat': 'Pretex 150 г', 'glue': 'OpSec WRS853'},
        1114: {'mat': 'Omega Silk 150 г', 'glue': 'OpSec WRS853'},
        1115: {'mat': 'Omega Silk 150 г', 'glue': 'OpSec WRS853'},
        1116: {'mat': 'Omega Silk 150 г', 'glue': 'OpSec WRS853'},
        1117: {'mat': 'Omega Silk 150 г', 'glue': 'OpSec WRS853'},
        1118: {'mat': 'Omega Silk 150 г', 'glue': 'OpSec WRS853'},
        1119: {'mat': 'Neobond 200 г', 'glue': 'OpSec WRS853'},
        1120: {'mat': 'Neobond 200 г', 'glue': 'OpSec WRS853'},
        1121: {'mat': 'Neobond 200 г', 'glue': 'OpSec WRS853'},
        1122: {'mat': 'Neobond 200 г', 'glue': 'OpSec WRS853'},
        1123: {'mat': 'Neobond 200 г', 'glue': 'OpSec WRS853'},
        1124: {'mat': 'Гознак 200 г', 'glue': 'Centro Grafico 125 WB'},
        1125: {'mat': 'Гознак 200 г', 'glue': 'Centro Grafico 125 WB'},
        1126: {'mat': 'Гознак 200 г', 'glue': 'Centro Grafico 125 WB'},
        1127: {'mat': 'Гознак 200 г', 'glue': 'Centro Grafico 125 WB'},
        1128: {'mat': 'Гознак 200 г', 'glue': 'Centro Grafico 125 WB'},
        1129: {'mat': 'Pretex 200 г', 'glue': 'Centro Grafico 125 WB'},
        1130: {'mat': 'Pretex 200 г', 'glue': 'Centro Grafico 125 WB'},
        1131: {'mat': 'Pretex 200 г', 'glue': 'Centro Grafico 125 WB'},
        1132: {'mat': 'Pretex 200 г', 'glue': 'Centro Grafico 125 WB'},
        1133: {'mat': 'Pretex 200 г', 'glue': 'Centro Grafico 125 WB'},
        1134: {'mat': 'Pretex 150 г', 'glue': 'Centro Grafico 125 WB'},
        1135: {'mat': 'Pretex 150 г', 'glue': 'Centro Grafico 125 WB'},
        1136: {'mat': 'Pretex 150 г', 'glue': 'Centro Grafico 125 WB'},
        1137: {'mat': 'Pretex 150 г', 'glue': 'Centro Grafico 125 WB'},
        1138: {'mat': 'Pretex 150 г', 'glue': 'Centro Grafico 125 WB'},
        1139: {'mat': 'Omega Silk 150 г', 'glue': 'Centro Grafico 125 WB'},
        1140: {'mat': 'Omega Silk 150 г', 'glue': 'Centro Grafico 125 WB'},
        1141: {'mat': 'Omega Silk 150 г', 'glue': 'Centro Grafico 125 WB'},
        1142: {'mat': 'Omega Silk 150 г', 'glue': 'Centro Grafico 125 WB'},
        1143: {'mat': 'Omega Silk 150 г', 'glue': 'Centro Grafico 125 WB'},
        1144: {'mat': 'Neobond 200 г', 'glue': 'Centro Grafico 125 WB'},
        1145: {'mat': 'Neobond 200 г', 'glue': 'Centro Grafico 125 WB'},
        1146: {'mat': 'Neobond 200 г', 'glue': 'Centro Grafico 125 WB'},
        1147: {'mat': 'Neobond 200 г', 'glue': 'Centro Grafico 125 WB'},
        1148: {'mat': 'Neobond 200 г', 'glue': 'Centro Grafico 125 WB'},
    },
    '2021-09-17_roller': {
        815: {'mat': 'Бумага офсетная для печати «Гознак 80 г»', 'glue_thickness': 'без клеевого слоя'},
        816: {'mat': 'Бумага офсетная для печати «Гознак 80 г»', 'glue_thickness': 'без клеевого слоя'},
        817: {'mat': 'Бумага офсетная для печати «Гознак 80 г»', 'glue_thickness': 'без клеевого слоя'},
        818: {'mat': 'Бумага офсетная для печати «Гознак 80 г»', 'glue_thickness': 'без клеевого слоя'},
        819: {'mat': 'Бумага офсетная для печати «Гознак 80 г»', 'glue_thickness': 'без клеевого слоя'},
        820: {'mat': 'Бумага офсетная для печати «Гознак 80 г»', 'glue_thickness': 'с клеевым слоем 1/3'},
        821: {'mat': 'Бумага офсетная для печати «Гознак 80 г»', 'glue_thickness': 'с клеевым слоем 1/3'},
        822: {'mat': 'Бумага офсетная для печати «Гознак 80 г»', 'glue_thickness': 'с клеевым слоем 1/3'},
        823: {'mat': 'Бумага офсетная для печати «Гознак 80 г»', 'glue_thickness': 'с клеевым слоем 1/3'},
        824: {'mat': 'Бумага офсетная для печати «Гознак 80 г»', 'glue_thickness': 'с клеевым слоем 1/3'},
        825: {'mat': 'Бумага офсетная для печати «Гознак 80 г»', 'glue_thickness': 'с клеевым слоем 1/4'},
        826: {'mat': 'Бумага офсетная для печати «Гознак 80 г»', 'glue_thickness': 'с клеевым слоем 1/4'},
        827: {'mat': 'Бумага офсетная для печати «Гознак 80 г»', 'glue_thickness': 'с клеевым слоем 1/4'},
        828: {'mat': 'Бумага офсетная для печати «Гознак 80 г»', 'glue_thickness': 'с клеевым слоем 1/4'},
        829: {'mat': 'Бумага офсетная для печати «Гознак 80 г»', 'glue_thickness': 'с клеевым слоем 1/4'},
        830: {'mat': 'Бумага офсетная для печати «Гознак 80 г»', 'glue_thickness': 'с клеевым слоем 1/5'},
        831: {'mat': 'Бумага офсетная для печати «Гознак 80 г»', 'glue_thickness': 'с клеевым слоем 1/5'},
        832: {'mat': 'Бумага офсетная для печати «Гознак 80 г»', 'glue_thickness': 'с клеевым слоем 1/5'},
        833: {'mat': 'Бумага офсетная для печати «Гознак 80 г»', 'glue_thickness': 'с клеевым слоем 1/5'},
        834: {'mat': 'Бумага офсетная для печати «Гознак 80 г»', 'glue_thickness': 'с клеевым слоем 1/5'},

    },
    '2021-09-10_no-glue-mats': {
        781: {'mat': 'Бумага офсетная для печати «Гознак 200 г»', 'glue': 'без клея'},
        782: {'mat': 'Бумага офсетная для печати «Гознак 200 г»', 'glue': 'без клея'},
        783: {'mat': 'Бумага офсетная для печати «Гознак 200 г»', 'glue': 'без клея'},
        784: {'mat': 'Бумага офсетная для печати «Гознак 200 г»', 'glue': 'без клея'},
        785: {'mat': 'Бумага офсетная для печати «Гознак 200 г»', 'glue': 'без клея'},
        786: {'mat': 'Синтетическая бумага «Pretex 200 г»', 'glue': 'без клея'},
        787: {'mat': 'Синтетическая бумага «Pretex 200 г»', 'glue': 'без клея'},
        788: {'mat': 'Синтетическая бумага «Pretex 200 г»', 'glue': 'без клея'},
        789: {'mat': 'Синтетическая бумага «Pretex 200 г»', 'glue': 'без клея'},
        790: {'mat': 'Синтетическая бумага «Pretex 200 г»', 'glue': 'без клея'},
        791: {'mat': 'Синтетическая бумага «Pretex 150 г»', 'glue': 'без клея'},
        792: {'mat': 'Синтетическая бумага «Pretex 150 г»', 'glue': 'без клея'},
        793: {'mat': 'Синтетическая бумага «Pretex 150 г»', 'glue': 'без клея'},
        794: {'mat': 'Синтетическая бумага «Pretex 150 г»', 'glue': 'без клея'},
        795: {'mat': 'Синтетическая бумага «Pretex 150 г»', 'glue': 'без клея'},
        796: {'mat': 'Бумага для печати «Omega Silk 150 г»', 'glue': 'без клея'},
        797: {'mat': 'Бумага для печати «Omega Silk 150 г»', 'glue': 'без клея'},
        798: {'mat': 'Бумага для печати «Omega Silk 150 г»', 'glue': 'без клея'},
        799: {'mat': 'Бумага для печати «Omega Silk 150 г»', 'glue': 'без клея'},
        800: {'mat': 'Бумага для печати «Omega Silk 150 г»', 'glue': 'без клея'},
        801: {'mat': 'Синтетическая бумага «Neobond 200 г»', 'glue': 'без клея'},
        802: {'mat': 'Синтетическая бумага «Neobond 200 г»', 'glue': 'без клея'},
        803: {'mat': 'Синтетическая бумага «Neobond 200 г»', 'glue': 'без клея'},
        804: {'mat': 'Синтетическая бумага «Neobond 200 г»', 'glue': 'без клея'},
        805: {'mat': 'Синтетическая бумага «Neobond 200 г»', 'glue': 'без клея'},
        806: {'mat': 'Синтетическая бумага «Neobond Classic 150 г»', 'glue': 'без клея'},
        807: {'mat': 'Синтетическая бумага «Neobond Classic 150 г»', 'glue': 'без клея'},
        808: {'mat': 'Синтетическая бумага «Neobond Classic 150 г»', 'glue': 'без клея'},
        809: {'mat': 'Синтетическая бумага «Neobond Classic 150 г»', 'glue': 'без клея'},
        810: {'mat': 'Синтетическая бумага «Neobond Classic 150 г»', 'glue': 'без клея'},
    },
    '2021-09-09_silk': {
        666: {'mat': 'Бумага офсетная для печати «Гознак 200 г»', 'pattern': 'Сетка', 'cell_size': 90},
        667: {'mat': 'Бумага офсетная для печати «Гознак 200 г»', 'pattern': 'Сетка', 'cell_size': 90},
        668: {'mat': 'Бумага офсетная для печати «Гознак 200 г»', 'pattern': 'Сетка', 'cell_size': 90},
        669: {'mat': 'Бумага офсетная для печати «Гознак 200 г»', 'pattern': 'Сетка', 'cell_size': 90},
        670: {'mat': 'Бумага офсетная для печати «Гознак 200 г»', 'pattern': 'Сетка', 'cell_size': 90},
        671: {'mat': 'Бумага офсетная для печати «Гознак 200 г»', 'pattern': 'Растр', 'cell_size': 90},
        672: {'mat': 'Бумага офсетная для печати «Гознак 200 г»', 'pattern': 'Растр', 'cell_size': 90},
        673: {'mat': 'Бумага офсетная для печати «Гознак 200 г»', 'pattern': 'Растр', 'cell_size': 90},
        674: {'mat': 'Бумага офсетная для печати «Гознак 200 г»', 'pattern': 'Растр', 'cell_size': 90},
        675: {'mat': 'Бумага офсетная для печати «Гознак 200 г»', 'pattern': 'Растр', 'cell_size': 90},
        676: {'mat': 'Синтетическая бумага «Pretex 200 г»', 'pattern': 'Сетка', 'cell_size': 90},
        677: {'mat': 'Синтетическая бумага «Pretex 200 г»', 'pattern': 'Сетка', 'cell_size': 90},
        678: {'mat': 'Синтетическая бумага «Pretex 200 г»', 'pattern': 'Сетка', 'cell_size': 90},
        679: {'mat': 'Синтетическая бумага «Pretex 200 г»', 'pattern': 'Сетка', 'cell_size': 90},
        680: {'mat': 'Синтетическая бумага «Pretex 200 г»', 'pattern': 'Сетка', 'cell_size': 90},
        681: {'mat': 'Синтетическая бумага «Pretex 200 г»', 'pattern': 'Растр', 'cell_size': 90},
        682: {'mat': 'Синтетическая бумага «Pretex 200 г»', 'pattern': 'Растр', 'cell_size': 90},
        683: {'mat': 'Синтетическая бумага «Pretex 200 г»', 'pattern': 'Растр', 'cell_size': 90},
        684: {'mat': 'Синтетическая бумага «Pretex 200 г»', 'pattern': 'Растр', 'cell_size': 90},
        685: {'mat': 'Синтетическая бумага «Pretex 200 г»', 'pattern': 'Растр', 'cell_size': 90},
        686: {'mat': 'Синтетическая бумага «Pretex 150 г»', 'pattern': 'Сетка', 'cell_size': 90},
        687: {'mat': 'Синтетическая бумага «Pretex 150 г»', 'pattern': 'Сетка', 'cell_size': 90},
        688: {'mat': 'Синтетическая бумага «Pretex 150 г»', 'pattern': 'Сетка', 'cell_size': 90},
        689: {'mat': 'Синтетическая бумага «Pretex 150 г»', 'pattern': 'Сетка', 'cell_size': 90},
        690: {'mat': 'Синтетическая бумага «Pretex 150 г»', 'pattern': 'Сетка', 'cell_size': 90},
        691: {'mat': 'Синтетическая бумага «Pretex 150 г»', 'pattern': 'Растр', 'cell_size': 90},
        692: {'mat': 'Синтетическая бумага «Pretex 150 г»', 'pattern': 'Растр', 'cell_size': 90},
        693: {'mat': 'Синтетическая бумага «Pretex 150 г»', 'pattern': 'Растр', 'cell_size': 90},
        694: {'mat': 'Синтетическая бумага «Pretex 150 г»', 'pattern': 'Растр', 'cell_size': 90},
        695: {'mat': 'Синтетическая бумага «Pretex 150 г»', 'pattern': 'Растр', 'cell_size': 90},
        711: {'mat': 'Бумага для печати «Omega Silk 150 г»', 'pattern': 'Сетка', 'cell_size': 90},
        712: {'mat': 'Бумага для печати «Omega Silk 150 г»', 'pattern': 'Сетка', 'cell_size': 90},
        713: {'mat': 'Бумага для печати «Omega Silk 150 г»', 'pattern': 'Сетка', 'cell_size': 90},
        714: {'mat': 'Бумага для печати «Omega Silk 150 г»', 'pattern': 'Сетка', 'cell_size': 90},
        715: {'mat': 'Бумага для печати «Omega Silk 150 г»', 'pattern': 'Сетка', 'cell_size': 90},
        716: {'mat': 'Бумага для печати «Omega Silk 150 г»', 'pattern': 'Растр', 'cell_size': 90},
        717: {'mat': 'Бумага для печати «Omega Silk 150 г»', 'pattern': 'Растр', 'cell_size': 90},
        718: {'mat': 'Бумага для печати «Omega Silk 150 г»', 'pattern': 'Растр', 'cell_size': 90},
        719: {'mat': 'Бумага для печати «Omega Silk 150 г»', 'pattern': 'Растр', 'cell_size': 90},
        720: {'mat': 'Бумага для печати «Omega Silk 150 г»', 'pattern': 'Растр', 'cell_size': 90},
        721: {'mat': 'Синтетическая бумага «Neobond 200 г»', 'pattern': 'Сетка', 'cell_size': 90},
        722: {'mat': 'Синтетическая бумага «Neobond 200 г»', 'pattern': 'Сетка', 'cell_size': 90},
        723: {'mat': 'Синтетическая бумага «Neobond 200 г»', 'pattern': 'Сетка', 'cell_size': 90},
        724: {'mat': 'Синтетическая бумага «Neobond 200 г»', 'pattern': 'Сетка', 'cell_size': 90},
        725: {'mat': 'Синтетическая бумага «Neobond 200 г»', 'pattern': 'Сетка', 'cell_size': 90},
        726: {'mat': 'Синтетическая бумага «Neobond 200 г»', 'pattern': 'Растр', 'cell_size': 90},
        727: {'mat': 'Синтетическая бумага «Neobond 200 г»', 'pattern': 'Растр', 'cell_size': 90},
        728: {'mat': 'Синтетическая бумага «Neobond 200 г»', 'pattern': 'Растр', 'cell_size': 90},
        729: {'mat': 'Синтетическая бумага «Neobond 200 г»', 'pattern': 'Растр', 'cell_size': 90},
        730: {'mat': 'Синтетическая бумага «Neobond 200 г»', 'pattern': 'Растр', 'cell_size': 90},
        731: {'mat': 'Бумага офсетная для печати «Гознак 200 г»', 'pattern': 'Сетка', 'cell_size': 100},
        732: {'mat': 'Бумага офсетная для печати «Гознак 200 г»', 'pattern': 'Сетка', 'cell_size': 100},
        733: {'mat': 'Бумага офсетная для печати «Гознак 200 г»', 'pattern': 'Сетка', 'cell_size': 100},
        734: {'mat': 'Бумага офсетная для печати «Гознак 200 г»', 'pattern': 'Сетка', 'cell_size': 100},
        735: {'mat': 'Бумага офсетная для печати «Гознак 200 г»', 'pattern': 'Сетка', 'cell_size': 100},
        736: {'mat': 'Бумага офсетная для печати «Гознак 200 г»', 'pattern': 'Растр', 'cell_size': 100},
        737: {'mat': 'Бумага офсетная для печати «Гознак 200 г»', 'pattern': 'Растр', 'cell_size': 100},
        738: {'mat': 'Бумага офсетная для печати «Гознак 200 г»', 'pattern': 'Растр', 'cell_size': 100},
        739: {'mat': 'Бумага офсетная для печати «Гознак 200 г»', 'pattern': 'Растр', 'cell_size': 100},
        740: {'mat': 'Бумага офсетная для печати «Гознак 200 г»', 'pattern': 'Растр', 'cell_size': 100},
        741: {'mat': 'Синтетическая бумага «Pretex 200 г»', 'pattern': 'Сетка', 'cell_size': 100},
        742: {'mat': 'Синтетическая бумага «Pretex 200 г»', 'pattern': 'Сетка', 'cell_size': 100},
        743: {'mat': 'Синтетическая бумага «Pretex 200 г»', 'pattern': 'Сетка', 'cell_size': 100},
        744: {'mat': 'Синтетическая бумага «Pretex 200 г»', 'pattern': 'Сетка', 'cell_size': 100},
        745: {'mat': 'Синтетическая бумага «Pretex 200 г»', 'pattern': 'Сетка', 'cell_size': 100},
        746: {'mat': 'Синтетическая бумага «Pretex 200 г»', 'pattern': 'Растр', 'cell_size': 100},
        747: {'mat': 'Синтетическая бумага «Pretex 200 г»', 'pattern': 'Растр', 'cell_size': 100},
        748: {'mat': 'Синтетическая бумага «Pretex 200 г»', 'pattern': 'Растр', 'cell_size': 100},
        749: {'mat': 'Синтетическая бумага «Pretex 200 г»', 'pattern': 'Растр', 'cell_size': 100},
        750: {'mat': 'Синтетическая бумага «Pretex 200 г»', 'pattern': 'Растр', 'cell_size': 100},
        751: {'mat': 'Синтетическая бумага «Pretex 150 г»', 'pattern': 'Сетка', 'cell_size': 100},
        752: {'mat': 'Синтетическая бумага «Pretex 150 г»', 'pattern': 'Сетка', 'cell_size': 100},
        753: {'mat': 'Синтетическая бумага «Pretex 150 г»', 'pattern': 'Сетка', 'cell_size': 100},
        754: {'mat': 'Синтетическая бумага «Pretex 150 г»', 'pattern': 'Сетка', 'cell_size': 100},
        755: {'mat': 'Синтетическая бумага «Pretex 150 г»', 'pattern': 'Сетка', 'cell_size': 100},
        756: {'mat': 'Синтетическая бумага «Pretex 150 г»', 'pattern': 'Растр', 'cell_size': 100},
        757: {'mat': 'Синтетическая бумага «Pretex 150 г»', 'pattern': 'Растр', 'cell_size': 100},
        758: {'mat': 'Синтетическая бумага «Pretex 150 г»', 'pattern': 'Растр', 'cell_size': 100},
        759: {'mat': 'Синтетическая бумага «Pretex 150 г»', 'pattern': 'Растр', 'cell_size': 100},
        760: {'mat': 'Синтетическая бумага «Pretex 150 г»', 'pattern': 'Растр', 'cell_size': 100},
        761: {'mat': 'Бумага для печати «Omega Silk 150 г»', 'pattern': 'Сетка', 'cell_size': 100},
        762: {'mat': 'Бумага для печати «Omega Silk 150 г»', 'pattern': 'Сетка', 'cell_size': 100},
        763: {'mat': 'Бумага для печати «Omega Silk 150 г»', 'pattern': 'Сетка', 'cell_size': 100},
        764: {'mat': 'Бумага для печати «Omega Silk 150 г»', 'pattern': 'Сетка', 'cell_size': 100},
        765: {'mat': 'Бумага для печати «Omega Silk 150 г»', 'pattern': 'Сетка', 'cell_size': 100},
        766: {'mat': 'Бумага для печати «Omega Silk 150 г»', 'pattern': 'Растр', 'cell_size': 100},
        767: {'mat': 'Бумага для печати «Omega Silk 150 г»', 'pattern': 'Растр', 'cell_size': 100},
        768: {'mat': 'Бумага для печати «Omega Silk 150 г»', 'pattern': 'Растр', 'cell_size': 100},
        769: {'mat': 'Бумага для печати «Omega Silk 150 г»', 'pattern': 'Растр', 'cell_size': 100},
        770: {'mat': 'Бумага для печати «Omega Silk 150 г»', 'pattern': 'Растр', 'cell_size': 100},
        771: {'mat': 'Синтетическая бумага «Neobond 200 г»', 'pattern': 'Сетка', 'cell_size': 100},
        772: {'mat': 'Синтетическая бумага «Neobond 200 г»', 'pattern': 'Сетка', 'cell_size': 100},
        773: {'mat': 'Синтетическая бумага «Neobond 200 г»', 'pattern': 'Сетка', 'cell_size': 100},
        774: {'mat': 'Синтетическая бумага «Neobond 200 г»', 'pattern': 'Сетка', 'cell_size': 100},
        775: {'mat': 'Синтетическая бумага «Neobond 200 г»', 'pattern': 'Сетка', 'cell_size': 100},
        776: {'mat': 'Синтетическая бумага «Neobond 200 г»', 'pattern': 'Растр', 'cell_size': 100},
        777: {'mat': 'Синтетическая бумага «Neobond 200 г»', 'pattern': 'Растр', 'cell_size': 100},
        778: {'mat': 'Синтетическая бумага «Neobond 200 г»', 'pattern': 'Растр', 'cell_size': 100},
        779: {'mat': 'Синтетическая бумага «Neobond 200 г»', 'pattern': 'Растр', 'cell_size': 100},
        780: {'mat': 'Синтетическая бумага «Neobond 200 г»', 'pattern': 'Растр', 'cell_size': 100},
        615: {'mat': 'Бумага офсетная для печати «Гознак 200 г»', 'pattern': 'Сетка', 'cell_size': 70},
        616: {'mat': 'Бумага офсетная для печати «Гознак 200 г»', 'pattern': 'Сетка', 'cell_size': 70},
        617: {'mat': 'Бумага офсетная для печати «Гознак 200 г»', 'pattern': 'Сетка', 'cell_size': 70},
        618: {'mat': 'Бумага офсетная для печати «Гознак 200 г»', 'pattern': 'Сетка', 'cell_size': 70},
        619: {'mat': 'Бумага офсетная для печати «Гознак 200 г»', 'pattern': 'Сетка', 'cell_size': 70},
        620: {'mat': 'Бумага офсетная для печати «Гознак 200 г»', 'pattern': 'Растр', 'cell_size': 70},
        621: {'mat': 'Бумага офсетная для печати «Гознак 200 г»', 'pattern': 'Растр', 'cell_size': 70},
        622: {'mat': 'Бумага офсетная для печати «Гознак 200 г»', 'pattern': 'Растр', 'cell_size': 70},
        623: {'mat': 'Бумага офсетная для печати «Гознак 200 г»', 'pattern': 'Растр', 'cell_size': 70},
        624: {'mat': 'Бумага офсетная для печати «Гознак 200 г»', 'pattern': 'Растр', 'cell_size': 70},
        625: {'mat': 'Синтетическая бумага «Pretex 200 г»', 'pattern': 'Сетка', 'cell_size': 70},
        626: {'mat': 'Синтетическая бумага «Pretex 200 г»', 'pattern': 'Сетка', 'cell_size': 70},
        627: {'mat': 'Синтетическая бумага «Pretex 200 г»', 'pattern': 'Сетка', 'cell_size': 70},
        628: {'mat': 'Синтетическая бумага «Pretex 200 г»', 'pattern': 'Сетка', 'cell_size': 70},
        629: {'mat': 'Синтетическая бумага «Pretex 200 г»', 'pattern': 'Сетка', 'cell_size': 70},
        630: {'mat': 'Синтетическая бумага «Pretex 200 г»', 'pattern': 'Растр', 'cell_size': 70},
        631: {'mat': 'Синтетическая бумага «Pretex 200 г»', 'pattern': 'Растр', 'cell_size': 70},
        632: {'mat': 'Синтетическая бумага «Pretex 200 г»', 'pattern': 'Растр', 'cell_size': 70},
        633: {'mat': 'Синтетическая бумага «Pretex 200 г»', 'pattern': 'Растр', 'cell_size': 70},
        634: {'mat': 'Синтетическая бумага «Pretex 200 г»', 'pattern': 'Растр', 'cell_size': 70},
        635: {'mat': 'Синтетическая бумага «Pretex 150 г»', 'pattern': 'Сетка', 'cell_size': 70},
        636: {'mat': 'Синтетическая бумага «Pretex 150 г»', 'pattern': 'Сетка', 'cell_size': 70},
        637: {'mat': 'Синтетическая бумага «Pretex 150 г»', 'pattern': 'Сетка', 'cell_size': 70},
        638: {'mat': 'Синтетическая бумага «Pretex 150 г»', 'pattern': 'Сетка', 'cell_size': 70},
        639: {'mat': 'Синтетическая бумага «Pretex 150 г»', 'pattern': 'Сетка', 'cell_size': 70},
        640: {'mat': 'Синтетическая бумага «Pretex 150 г»', 'pattern': 'Растр', 'cell_size': 70},
        641: {'mat': 'Синтетическая бумага «Pretex 150 г»', 'pattern': 'Растр', 'cell_size': 70},
        642: {'mat': 'Синтетическая бумага «Pretex 150 г»', 'pattern': 'Растр', 'cell_size': 70},
        643: {'mat': 'Синтетическая бумага «Pretex 150 г»', 'pattern': 'Растр', 'cell_size': 70},
        644: {'mat': 'Синтетическая бумага «Pretex 150 г»', 'pattern': 'Растр', 'cell_size': 70},
        645: {'mat': 'Бумага для печати «Omega Silk 150 г»', 'pattern': 'Сетка', 'cell_size': 70},
        646: {'mat': 'Бумага для печати «Omega Silk 150 г»', 'pattern': 'Сетка', 'cell_size': 70},
        647: {'mat': 'Бумага для печати «Omega Silk 150 г»', 'pattern': 'Сетка', 'cell_size': 70},
        648: {'mat': 'Бумага для печати «Omega Silk 150 г»', 'pattern': 'Сетка', 'cell_size': 70},
        649: {'mat': 'Бумага для печати «Omega Silk 150 г»', 'pattern': 'Сетка', 'cell_size': 70},
        650: {'mat': 'Бумага для печати «Omega Silk 150 г»', 'pattern': 'Растр', 'cell_size': 70},
        651: {'mat': 'Бумага для печати «Omega Silk 150 г»', 'pattern': 'Растр', 'cell_size': 70},
        652: {'mat': 'Бумага для печати «Omega Silk 150 г»', 'pattern': 'Растр', 'cell_size': 70},
        653: {'mat': 'Бумага для печати «Omega Silk 150 г»', 'pattern': 'Растр', 'cell_size': 70},
        654: {'mat': 'Бумага для печати «Omega Silk 150 г»', 'pattern': 'Растр', 'cell_size': 70},
        655: {'mat': 'Синтетическая бумага «Neobond 200 г»', 'pattern': 'Сетка', 'cell_size': 70},
        656: {'mat': 'Синтетическая бумага «Neobond 200 г»', 'pattern': 'Сетка', 'cell_size': 70},
        657: {'mat': 'Синтетическая бумага «Neobond 200 г»', 'pattern': 'Сетка', 'cell_size': 70},
        658: {'mat': 'Синтетическая бумага «Neobond 200 г»', 'pattern': 'Сетка', 'cell_size': 70},
        659: {'mat': 'Синтетическая бумага «Neobond 200 г»', 'pattern': 'Сетка', 'cell_size': 70},
        660: {'mat': 'Синтетическая бумага «Neobond 200 г»', 'pattern': 'Растр', 'cell_size': 70},
        661: {'mat': 'Синтетическая бумага «Neobond 200 г»', 'pattern': 'Растр', 'cell_size': 70},
        662: {'mat': 'Синтетическая бумага «Neobond 200 г»', 'pattern': 'Растр', 'cell_size': 70},
        663: {'mat': 'Синтетическая бумага «Neobond 200 г»', 'pattern': 'Растр', 'cell_size': 70},
        664: {'mat': 'Синтетическая бумага «Neobond 200 г»', 'pattern': 'Растр', 'cell_size': 70},
        665: {'mat': 'Синтетическая бумага «Neobond 200 г»', 'pattern': 'Растр', 'cell_size': 70},
    },
    # {
    #
    # }
}

import pandas as pd
import seaborn as sb

df_f = pd.read_excel('master_filtered.xlsx', engine='openpyxl')

batches = ['2021-09-30_glues', '2021-09-17_roller', '2021-09-10_no-glue-mats', '2021-09-09_silk']

pairs =[[v['mat'], v['glue']] for k, v in mats[batches[0]].items()]
vars1 = set(v for v, _ in pairs)
vars2 = set(v for _, v in pairs)
pairs = list(itertools.product(vars1, vars2))

df_plot = df_f
for var1, var2 in pairs[:2]:
    data = df_plot.loc[(df_plot['mat'] == var1) & (df_plot['glue'] == var2)]

    ax = sb.lineplot(data=data, x='L(mm)', y='F(N)', hue='measure', palette='viridis')
    ax.set(xlim=(0, 4), title=f'{var1}   +   {var2}')

    fig = ax.get_figure()
    fig.savefig(f'png/{var1}#{var2}.png', dpi=200)
    fig.clf()
